services:
  backend:
    build: .
    container_name: hr-backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env.prod
    networks:
      - marstech-network

  mysql:
    image: mysql:8.0
    container_name: marstech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: marstech_hr
      MYSQL_USER: marstech
      MYSQL_PASSWORD: marstechpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - marstech-network

volumes:
  mysql_data:

networks:
  marstech-network:
